### ISSUE TITLE
Проверить документацию и составить список на актуализацию

### ISSUE THREAD

**Issue by distol** [flant/dapp#108]

**Comment by alexey-igrychev** [comment]
список составлен

**Comment by distol** [comment]
А где список-то??? Где он?

**Comment by alexey-igrychev** [comment]
@distol 
в g-документах: в основном и сегодняшнем

**Comment by distol** [comment]
Ну вот плохо так делать. Если мы хотим открытую разработку, то надо как-то перестроить процесс коммуникации. Ладно, будем стараться.
