### ISSUE TITLE
Параметр --introspect-error не срабатывает при падении на сборке стадии артефакта

### ISSUE THREAD

**Issue by distorhead** [flant/dapp#110]
Команда: `dapp dimg build --verbose --dev --introspect-error`

![image](https://cloud.githubusercontent.com/assets/1161992/23854586/0c2c2b8a-0803-11e7-9895-819bd8b57a4c.png)

**Comment by distorhead** [comment]
Может быть связано, может быть нет, если запустить команду `dapp dimg build --verbose --dev --introspect-artifact-stage g_a_pre_install_patch`, то получается тот же результат + сообщение `docker: Error response from daemon: containerd: container not started.`:

![image](https://cloud.githubusercontent.com/assets/1161992/23854760/d1c4b452-0803-11e7-95ba-f405becdf94f.png)

Хорошо бы это тоже проверить.

**Comment by distorhead** [comment]
При сборке без артефакта тоже самое, с артифактом это не связано. Introspect error сломался где-то в 0.8/0.9.

**Comment by diafour** [comment]
посмотрел
