### ISSUE TITLE
Непонятные символы в выхлопе при сборке Gitlab

### ISSUE THREAD

**Issue by kobel169** [flant/dapp#112]
При сборке в Gitlab версией 0.8 Вижу ошибку от tput, а так же по мере сборки Непонятные буквы перед статусом этапа. По скриншоту пример.
![image](https://cloud.githubusercontent.com/assets/153952/23858513/b57d3cac-0811-11e7-8ca4-e919761cbb09.png)

**Comment by alexey-igrychev** [comment]
Непонятные символы — первые буквы стадий, которые собираются.
Происходит в связи с тем, что не удалось узнать ширину терминала от tput: лог адаптируется под размер терминала.
Можно установить на этот случай размер по умолчанию, например, 80 символов.
