### ISSUE TITLE
Конфигурационный файл с опциями dapp по умолчанию

### ISSUE THREAD

**Issue by kobel169** [flant/dapp#113]
Хотелось бы иметь возможность описать опции по умолчанию для вызова dapp.
такие как --verbose, --dev, --color, --build-dir, --quiet. 

К примеру на машине разработки всегда требуются --dev, --verbose, 
на машине сборки иметь возможность прозрачно переопределить  --build-dir глобально, не исправляя все скрипты деплоев.

**Comment by distorhead** [comment]
Предлагаю сделать файл `.dapp_config`, в котором в формате yaml можно указать ключи: `color`, `dev`, `build-dir`, `verbose`.

Приоритет: cli, `.dapp_config`, значение по умолчанию.

**Comment by distorhead** [comment]
Остается понять как сделать удобно для разработчика: чтобы `--dev` был всегда включен локально, но не на сборочном сервере.
