### ISSUE TITLE
Unable to remove project tmp dir

### ISSUE THREAD

**Issue by kovetskiy** [flant/dapp#1166]
Hello, I tried dapp 1.0.0 alpha and run into problem that dapp was unable to remove project tmp directory, latest output is:
```
npm WARN company No repository field.
npm WARN company No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 999 packages from 630 contributors and audited 13066 packages in 94.629s
found 0 vulnerabilities

# Building image dimgstage-nodejs-backend-auth:44d4ad5a0836837889d58fb2485914b45f794b987ae4107195bcaa21c042e89a for dimg/nodejs-backend-auth stage/setup
# Using cached image dimgstage-nodejs-backend-auth:28347249896a7fe21822d2a203e2e052d8ab5703bead7c6098e9591119a40b6a for dimg/nodejs-backend/auth/ stage/from
# Building image dimgstage-nodejs-backend-auth:2f24c247f6d2ba3ddcbe7286effe941d27502caa8fc8fb5ec53ae697dc647f1a for dimg/nodejs-backend/auth/ stage/after_setup_artifact
WARNING: unable to remove project tmp dir /tmp/dapp-502848276: remove /tmp/dapp-502848276/dimg/nodejs-backend/auth/artifact/nodejs-backend-auth/4e99338780ae02474e1e8480a2de401a0d56d307e0aab3c40320eb9cc90fe670/nodemon-debug.json: permission denied
```

inside of docker containers we run everything by root user, we run dapp by special user (gitlab-runner), and as result that directory files of /tmp/dapp-<id-here>/ are owned by root:root which leads to problem with permissions

I took a look at code 
https://github.com/flant/dapp/blob/master/pkg/build/stage/base.go#L86
https://github.com/flant/dapp/blob/master/pkg/build/stage/base.go#L178
and as far as I understand the tmp_dir is mounted into container.

Is there any possible workaround agains this issue? I'm not really willing to run gitlab ci by root user and it also would be weird to have user gitlab-runner inside of docker containers just to fix the issue with removing directories.

**Comment by distorhead** [comment]
https://github.com/flant/dapp/releases/tag/v1.0.0-alpha.2
