### ISSUE TITLE
Использование аргументов при стадиях beforeInstall && install

### ISSUE THREAD

**Issue by skyfall174** [flant/dapp#1172]
У меня возникла проблема, во время стадий install, beforeInstall, setup. А именно мне нужно передавать переменную окружения, которую я буду использовать при инсталировании. Для этого используются в Docker аргументы, однако я не увидел нигде в документации упоминания об аргументах.

Может есть какой-то другой способ решения данной проблемы?

Спасибо за ответ

**Comment by alexey-igrychev** [comment]
If need to use special environment variables in build-time, you can use a [base image](http://flant.github.io/dapp/reference/build/base_image.html) with these variables or implement exporting environment variables right in [user stage](http://flant.github.io/dapp/reference/build/assembly_instructions.html#what-is-user-stages) instructions.

```
dimg: ~
from: alpine
shell:
  beforeInstall:
  {{- include "export common environment variables" . }}
  ...
  install:
  {{- include "export common environment variables" . }}
  ...
  beforeSetup:
  {{- include "export common environment variables" . }}
  ...
  
{{- define "export common environment variables" }}
  - export VAR1=VAL
  - export VAR2=VAL
{{- end }}
```

**Comment by alexey-igrychev** [comment]
Also, you can read [FAQ: Can I set an environment variable to use it during build?](http://flant.github.io/dapp/faq.html#dappfile-4).

**Comment by skyfall174** [comment]
@alexey-igrychev Thank you for fast response
