### ISSUE TITLE
Stages diagram

### ISSUE THREAD

**Issue by diafour** [flant/dapp#13]
Diagram of stages (build life cycle) will help a lot to understand dapp.
Example: https://docs.chef.io/chef_client.html#the-chef-client-title-run

**Comment by distorhead** [comment]
This diagram may help to understand chef builder dependencies: ![chef dependencies](https://docs.google.com/drawings/d/1zAAmxIqpfONBp9u3kZvd_KpCukvH_htvkd--OWtWt54/pub?w=1440&h=1080)

**Comment by distorhead** [comment]
https://flant.github.io/dapp/stages_diagram.html

**Comment by diafour** [comment]
fixed in #180
