### ISSUE TITLE
Поддержка произвольных рецептов в dimod

### ISSUE THREAD

**Issue by distorhead** [flant/dapp#132]
Релиз-инженеру приложения собираемого через dapp нужна возможность добавлять произвольные рецепты в dimod'ы и задействовать их при сборке стадий, чтобы исключить копирование одинакового кода рецептов.

### Подробности
Текущая схема допускает запуск на стадии лишь одного рецепта из dimod с именем, соответствующим имени стадии. Этот рецепт не может включать в себя другие репецепты. Такое ограничение открывает возможность беспроблемного кеширования кода рецептов сборки стадий. Однако мешает нормальной организации кода без копирования.

Один из вариантов решения: включать дополнительные рецепты в стадии на основе использования директивы include_recipe в entrypoint-рецептах.

**Comment by diafour** [comment]
chef builder is deprecated
