### ISSUE TITLE
Не работает сборка из-за конфликта файловых локов

### ISSUE THREAD

**Issue by distorhead** [flant/dapp#134]
Генерировать имена файловых локов через хэш функцию. Сейчас имя файла отрезается до 32 символов. Надо брать хэш от имени лока (например, murmurhash 32bit). Имя файла представлять как hex, получатся 8-символьные фиксированные имена.

Disclaimer. Стоит рассматривать эту задачу как быстрый наколенный хак, чтобы сейчас не решать проблему с TarWriter.

**Comment by alexey-igrychev** [comment]
#98
