### ISSUE TITLE
Предикативные методы в коде стадий

### ISSUE THREAD

**Issue by alexey-igrychev** [flant/dapp#141]
Как разработчик dapp, я хочу иметь актуальный набор предикативных методов в коде стадий, чтобы исключить их избыточность и неоднозначность при использовании.

**Comment by diafour** [comment]
@alexey-igrychev про что эта задача? "предикативных методов в коде стадий" — это что?

**Comment by alexey-igrychev** [comment]
@diafour про рефакторинг; методы заканчивающиеся на '?'.
