### ISSUE TITLE
Сообщение о вендоринге cookbook'ов без verbose

### ISSUE THREAD

**Issue by distorhead** [flant/dapp#169]
Если verbose режим не включен, то сейчас при вендоринге cookbook'ов на экран ничего не выводится, что вводит в замешательство. Надо выводить то же сообщение, что и при verbose, но без подробного лога от berks.

**Comment by diafour** [comment]
Аналогичная штука, но про docker.from. Если нет скаченного образа, то dapp dimg build просто "висит". Хотя

**Comment by diafour** [comment]
chef builder is deprecated
