### ISSUE TITLE
Новые переменные CI в gitlab 9.0

### ISSUE THREAD

**Issue by diafour** [flant/dapp#182]
Нужно добавить поддержку новых переменных среды, появившихся в gitlab 9.0: https://about.gitlab.com/2017/03/22/gitlab-9-0-released/#gitlab-ci-ce-ee

Поддержка нужна и для ветки 0.7.

**Comment by diafour** [comment]
Переходу на 9.0 не мешает, т.к. пока поддерживается два набора переменных. В каком релизе останутся только новые - пока нет информации.

**Comment by ev4ern** [comment]
что мешает сделать в Dappfile ENV['CI_BUILD_REF_NAME'] или вроде того?

**Comment by diafour** [comment]
https://github.com/flant/dapp/blob/0.13.3/lib/dapp/dimg/cli/command/dimg/push.rb#L34-L42

https://github.com/flant/dapp/blob/0.13.3/lib/dapp/dimg/dimg/tags.rb#L50-L52
