### ISSUE TITLE
Have you seen Roker before?

### ISSUE THREAD

**Issue by korsarnsk** [flant/dapp#20]
It seems that Rocker solves similar task https://github.com/grammarly/rocker

**Comment by distol** [comment]
Yes, we have seen Rocker before, and have used some ideas from it. But Rocker solves only small amount of problems we have solved. For now, the biggest problem of dapp is a lack of documentation. No one knows, what dapp actually can do. We have only "raw man" in Russian about DSL and command itself, but there are no features descriptions, usage scenarios, etc.

The best source for information, for now, is [the presentation from the HL++2016](goo.gl/2WNOGR) conference in Moscow, but it also contains description only of, maybe, a half of the features.

We will work on documentation in the following months and believe, that it will fully answer your question.
