### ISSUE TITLE
Не верные ссылки на страницу "шеф сборщик" в документации

### ISSUE THREAD

**Issue by diafour** [flant/dapp#21]
На странице chef_directives не верные ссылки. Должны быть на шеф сборщик, а ссылаются на базовые директивы. Вот например в конце определения [chef-recipe](http://flant.github.io/dapp/chef_directives.html#chef-recipe-<recipe>-<recipe>-<recipe>-…)

**Comment by alexey-igrychev** [comment]
Закрываю в пользу #108
