### ISSUE TITLE
Сборка падает из-за того что в /.dapp/tmp/archives/ нет архива репы.

### ISSUE THREAD

**Issue by ekonomizer** [flant/dapp#233]
Привет. Я работаю в компании socialquantum, мы решили задействовать для сборки docker контейнера ваш гем.
У меня возникает ошибка с добавлением репозитория в темповую директорию. Уже не знаю куда копать(

Dappfile
dimg 'm3_server' do
  docker.from 'node:7.10-slim'

  git do
    add '/' do
      to '/server'
    end
  end

  shell do
    setup do
      run 'ls -la /'
      run 'ls -la /server/'
      run 'ls -la'
    end
  end
end

Образ нормально собирается локально.

Но я использую Gitlab CI, 
build:1.1:
  script:
    - dapp dimg cleanup
    - dapp dimg mrproper --all
    - dapp dimg build --verbose
И сборочный контейнер CI Runner хостится на амазоне. 
И внутри него сборка не получается. Почему то git репозиторий не попадает в /.dapp/tmp/ директорию.

root@374552e2b567:/home/gitlab-runner/builds/eff343e5/0/match3/m3_server# dapp d
img build --verbose --introspect-before-error
match3
  From ...                                                   [OK] 0.46 sec
    signature: dimgstage-m3_server:25f4aad95545c876af9383f86ecf6a88cd499e3c2d2e9
382e3b423f95ff43a7f
  Before install                                          [EMPTY]
    signature: dimgstage-m3_server:25f4aad95545c876af9383f86ecf6a88cd499e3c2d2e9
382e3b423f95ff43a7f
  Before install artifact                                 [EMPTY]
    signature: dimgstage-m3_server:25f4aad95545c876af9383f86ecf6a88cd499e3c2d2e9
382e3b423f95ff43a7f
  Git artifacts dependencies ...                             [OK] 0.41 sec
    signature: dimgstage-m3_server:32977db942f30044f45695d39404fcf0fd74d2566e75a
893b0fbfe5cd254eff0
  Git artifacts: create archive ...   Launched command: `/.dapp/deps/base/0.1.15
/bin/install  -d /server_js && /.dapp/deps/base/0.1.15/bin/tar -xf /.dapp/tmp/ar
chives/own_abcf3df0a0f7a9c3e01a92bef3615dbf80ef5e2b.tar -C /server_js`
                     [FAILED] 0.27 sec
    signature: dimgstage-m3_server:b362a1e22050c0cd5dbc6b4d22d8a29420c2346369948
2deeb1da4f266439c1f
bash-4.3# ls -la .dapp/tmp/archives/
total 8
drwxr-xr-x 2 root root 4096 May 22 10:48 .
drwxr-xr-x 4 root root 4096 May 22 10:48 ..
bash-4.3#

Подскажите плиз в чем может быть причина.

**Comment by ekonomizer** [comment]
Андрей, добрый день!

Давайте решим вашу проблему. Попробуйте запустить с опцией `--tmp-dir-prefix=/some-location-different-from-tmp` (dapp генерируют tmp директорию на каждую сборку).


Создал "/tmp_dir" в сборочном контейнере. Запустил с --tmp-dir-prefix=/tmp_dir

root@374552e2b567:/home/gitlab-runner/builds/eff343e5/0/match3/m3_server# dapp d
img build --verbose --tmp-dir-prefix=/tmp_dir --introspect-before-error
match3
  From ...                                                   [OK] 0.38 sec
    signature: dimgstage-m3_server:25f4aad95545c876af9383f86ecf6a88cd499e3c2d2e9
382e3b423f95ff43a7f
  Before install                                          [EMPTY]
    signature: dimgstage-m3_server:25f4aad95545c876af9383f86ecf6a88cd499e3c2d2e9
382e3b423f95ff43a7f
  Before install artifact                                 [EMPTY]
    signature: dimgstage-m3_server:25f4aad95545c876af9383f86ecf6a88cd499e3c2d2e9
382e3b423f95ff43a7f
  Git artifacts dependencies ...                             [OK] 0.43 sec
    signature: dimgstage-m3_server:32977db942f30044f45695d39404fcf0fd74d2566e75a
893b0fbfe5cd254eff0
  Git artifacts: create archive ...   Launched command: `/.dapp/deps/base/0.1.15
/bin/install  -d /server_js && /.dapp/deps/base/0.1.15/bin/tar -xf /.dapp/tmp/ar
chives/own_abcf3df0a0f7a9c3e01a92bef3615dbf80ef5e2b.tar -C /server_js`
                     [FAILED] 0.34 sec
    signature: dimgstage-m3_server:b362a1e22050c0cd5dbc6b4d22d8a29420c2346369948
2deeb1da4f266439c1f
bash-4.3# exit
Stacktrace dumped to /tmp/dapp-stacktrace-f220103e-0e5a-427d-9639-acf6ffd17bff.o
ut
>>> START STREAM
/.dapp/deps/base/0.1.15/bin/tar: /.dapp/tmp/archives/own_abcf3df0a0f7a9c3e01a92b
ef3615dbf80ef5e2b.tar: Cannot open: No such file or directory
/.dapp/deps/base/0.1.15/bin/tar: Error is not recoverable: exiting now
>>> END STREAM

**Comment by distorhead** [comment]
Похоже, что проблема в монтировании директорий в docker-контейнер.

Пальцем в небо: вот тут обсуждают похожую по симптомам проблему:
> Docker mount cannot access EFS mount
https://forums.aws.amazon.com/thread.jspa?threadID=235119

Надо проверить простой случай:

```
mkdir /tmp/testdir1
touch /tmp/testdir1/HELLO
docker run -ti --rm -v /tmp/testdir1:/tmp/testdir1 node:7.10-slim ls -la /tmp/testdir1
```

И попробовать принудительно перезапустить docker-сервер.

**Comment by ekonomizer** [comment]
Спасибо дело именно в монтировании директории. Будем думать как это победить
