### ISSUE TITLE
Доступ из ruby кода dapp к ФС сборочного контейнера

### ISSUE THREAD

**Issue by distorhead** [flant/dapp#27]
Как разработчик dapp я хочу отказаться от служебных вызовов любых консольных утилит внутри сборочного контейнера (при сборке образов), это дополнительно позволит отказаться от механизма dappdeps для основного функционала, проблем с libc, scratch-образами и пр.

_Дополнительная информация_

Фактически, нужно придумать как ОС-безопасно ходить в ФС контейнера и переписать работу с git apply, tar, find, install и пр. на соответствующие ruby библиотеки.

**Comment by distol** [comment]
Сам вопрос возник из-за того, что были проблемы с зависимостью dappdeps от конкретной версии libc. Закрываю в пользу #45 .
