### ISSUE TITLE
Отказ от Berksfile и metadata.rb

### ISSUE THREAD

**Issue by alexey-igrychev** [flant/dapp#31]
Как релиз-инженер (chef-приложения), я хочу указывать cookbook'и в Dappfile, чтобы:
- избежать ошибок, связанных с забытыми файлами chef-проекта Berksfile, Berksfile.lock и metadata.rb;
- упростить и повысить понятность описания сборки chef-приложения.

_Детали реализации_

- metadata.rb — генерируем
- Berksfile — генерируем
- ­от проверки Berksfile.lock — отказываемся
  - Зачем была проверка?
    - Чтобы был закоммичен актуальный Berksfile.lock
    - В Berksfile.lock фиксируются версии cookbook'ов
- Для стадии chef_cookbooks используем .chefinit вместо .dapp_chef.
  - Дополнительно рассматриваем возможность отказаться от стадии chef_cookbooks, сделав ее явной (готовый кусок кода для Dappfile).
- Для зависимостей в Dappfile указывать:
  - Название cookbook
    - есть dimod
      - для вкл. dimod автоматом добавляется соотв. cookbook
    - есть просто сторонний cookbook-зависимость (например apt)
  - Откуда брать (git, github, без указания)
  - Version constraint

**Comment by distol** [comment]
@distorhead, не забыть в тестовом проекте сделать пример, как заменить выпиленую стадию chef_cookbooks, ручными действиями (с использованием artifact и пр.).
