### ISSUE TITLE
Стадия patch (final)

### ISSUE THREAD

**Issue by distorhead** [flant/dapp#34]
Релиз-инженеру приложения нужна возможность добавлять инструкции сборки для shell и chef сборщиков, которые отрабатывали бы после стадии setup, т.е. в последнюю очередь, чтобы была возможность изменять уже собранный образ в кеше, когда пересборка невозможна. Например, подменить библиотеку OpenSSL для срочного хотфикса бага в приложении, которое несколько лет не собиралось и пересобирать просто страшно.

**Comment by distorhead** [comment]
Отказ: лучше через отдельный from.

**Comment by diafour** [comment]
В описанном случае, когда пересобирать не представляется возможным, проще забить на кэш, затэгировать существующий готовый образ и использовать его в качестве from для дальнейших сборок.
