### ISSUE TITLE
Если в имени репозитория есть upper-case символы - сборка падает

### ISSUE THREAD

**Issue by eugerm** [flant/dapp#341]
Если репозиторий называется Uppercaserepo, то на последнем этапе (для docker) сборка падает с подобныйм сообщением:
`Stacktrace dumped to /tmp/dapp-stacktrace-e250ddc5-2ae4-4ee0-8396-eb2b6a9f9ef3.out >>> START STREAM Error parsing reference: "dimgstage-Uppercaserepo:d694aba029e8f89abafd035b959e84dc9c65fcafb9bbfb28b0b056a6b7b6f08a" is not a valid repository/tag >>> END STREAM`
Это особенность поведения docker. Описано здесь - https://github.com/spotify/docker-maven-plugin/issues/264
http://screencloud.net/v/a8BP3

> https://docs.docker.com/engine/reference/commandline/tag/ says you can tag images with uppercase letters. build -t tags doesn't follow that same logic

Было бы здорово иметь более ясное сообщение об ошибке.

**Comment by alexey-igrychev** [comment]
https://github.com/flant/dapp/pull/473
