### ISSUE TITLE
Использовать kubectl вместо прямого чтения конфига .kube/config

### ISSUE THREAD

**Issue by distorhead** [flant/dapp#362]
```
kubectl config view --minify=true --raw -o json-path=...
```

**Comment by diafour** [comment]
dapp может быть запущен в k8s, предлагаю такой алгоритм, аналогичный другому проекту:

- Определить, доступен ли in-cluster конфиг, если да, читать его.
- Определить, доступен ли kubectl, если да, то `kubectl config view`.
- Читать напрямую .kube/config

**Comment by distorhead** [comment]
Связано с #668

**Comment by distorhead** [comment]
https://github.com/flant/dapp/pull/717

Еще надо доделать in-cluster, но это не приоритет.
