### ISSUE TITLE
Установка с помощью gem install dapp

### ISSUE THREAD

**Issue by kixiro** [flant/dapp#363]
В README не указано зависимостей ruby-dev и dpkg-config, при установке без них не собирается.
Проверено на Ubuntu 16.04

**Comment by diafour** [comment]
Поправить описание установки.
Заодно добавить Vagrantfile из последней статьи с хабра, чтобы можно было не устанавливать dapp в систему, а попробовать сборку в виртуалке с докером.

**Comment by distorhead** [comment]
Зависимости специфичны и зависят от того, как поставлен ruby в систему. В README описано с рассчетом, что ruby уже как-то установлен.

**Comment by kixiro** [comment]
В Readme указано, что должна стоять Ruby > 2.1, про dev пакет там ничего нет.
