### ISSUE TITLE
hub.docker.com

### ISSUE THREAD

**Issue by antonmarin** [flant/dapp#364]
Планируете ли вы собрать образ для hub.docker.com? Думаю было бы удобно запускать dapp также как docker:dind

**Comment by diafour** [comment]
Будут проблемы с монтированием директорий (build_dir, tmp_dir). Подробнее обсуждали в telegram группе https://t.me/dapp_ru/157
Скорее всего возможно запустить, но пока для нас это не критичная проблема. Как-нибудь поэкспериментируем.

**Comment by antonmarin** [comment]
Может держать в виде сервиса?
У нас сейчас для постройки контейнеров используется такая схема:
Gitlab runner(kubernetes executor) -> docker:latest(выполняет постройку) -> docker:dind(держим в виде сервиса)
Так получилось и кэш сохранить и постройку в изоляции делать

**Comment by antonmarin** [comment]
Уже понял что держать в виде сервиса не имеет смысла ((
