### ISSUE TITLE
Добавить examples и best practices для разных языков

### ISSUE THREAD

**Issue by ev4ern** [flant/dapp#387]
Очень хотелось читать документацию с примерами реального использования

**Comment by diafour** [comment]
Для php и go есть примеры в статье https://habrahabr.ru/company/flant/blog/336212/
Но конечно лучше, чтобы это всё было и в документации.

**Comment by may-cat** [comment]
Готовлю видео-вебинарчики с реальными аппками, думаю, это закроет боль.

**Comment by alexey-igrychev** [comment]
https://flant.github.io/dapp/how_to/installation.html
New ones are coming
