### ISSUE TITLE
Режим “разверни мне вот эти модули локально для разработки”

### ISSUE THREAD

**Issue by distorhead** [flant/dapp#43]
Как релиз-инженер приложения я хочу быстро разворачивать локальное окружение для dapp проекта для внесения изменений не только в проект, но и в dimod-модули, указаные в Dappfile.

_Детали реализации_

* Команда `dapp dev clone <git-url>`
  * Клонирует репо в текущую директорию.
  * Берет все dimod'ы, указанные в Berksfile и клонирует в текущую директорию.
  * Заменяет пути до исходников dimod'ов в Berksfile на локальные.
* Вопросы:
  * Что делать, когда Berksfile будет генериться автоматом?
  * Нужна ли противоположная команда, которая заменит пути в Berksfile обратно?

**Comment by diafour** [comment]
chef builder is deprecated
