### ISSUE TITLE
Убрать зависимость dappdeps от конкретной версии libc

### ISSUE THREAD

**Issue by alexey-igrychev** [flant/dapp#45]
Как релиз-инженер приложения, я хочу чтобы сборщик не зависел от библиотеки libc внутри собираемого контейнера, чтобы иметь возможность собирать образ приложения из произвольного docker-образа.

_Детали реализации_
- Dappdeps зависит от libc в docker.from образе — проблема.
- Пока известно только про libc, возможно что-то еще.
  - В целом dappdeps должен быть автономен, но надо выяснить подробнее какие еще библиотеки считаются базовыми в chef/omnibus (возможно больше никакие).

**Comment by distol** [comment]
Прочитав https://github.com/phusion/traveling-ruby#why-not-just-statically-link-the-ruby-binary пришли к следующему:
1. Пересобираем dappdeps в максимально старом окружении, так чтобы получившиеся бинарники имели только символы как можно более старой версии libc.
2. Пишем автотесты, которые проверяют работу всех требуемых нам утилит (видел в коде dapp массив) на наборе образов (пока достаточно alpine-ruby, ubuntu:12.04, ubuntu:14.04, ubuntu:16.04, centos:5, centos:6, centos:7). Думаю, что достаточно проверять утилиты просто на факт запускабельности.

**Comment by distorhead** [comment]
Поправка: попробовать собрать в debian:6, в котором glibc 2.11.

**Comment by distorhead** [comment]
Сделано в PR #163
