### ISSUE TITLE
Встроенная документация в утилиту dapp

### ISSUE THREAD

**Issue by alexey-igrychev** [flant/dapp#50]
Как пользователь dapp я хочу получать наиболее полную и актуальную справку по командам утилиты dapp из командной строки, чтобы доступ к документации был всегда под рукой.
- Зайти посмотреть документацию на сайт, если забыл — долго
- Встроенная справка по командам в текущей версии неполна и НЕ может служить первичным руководством, понятна только после чтения полной документации с примерами
  - Например, по командам push, spush — по встроенной справке вообще ничего не понятно

Как пользователь dapp я хочу иметь возможность просматривать полную документацию на сайте проекта в том случае, если на момент просмотра нет возможности запустить команду dapp в терминале.

Как разработчик dapp я хочу описывать документацию в одном месте и для сайта, и для встроенной в dapp справки, чтобы избежать дублирования одинаковой информации.

_Детали реализации_
- Gem для форматированного вывода markdown в консоль
  - https://github.com/ttscoff/mdless
  - Использовать гем как есть не получится
    - Не доделан и рассчитан только на cli
  - Можно вынуть оттуда движок и создать свой гем, пригодный для использования в dapp
    - Интерфейс должен быть что-то типа: `format_markdown(<markdown-string>) => <string>`
- Документация по командам должна быть разбита на отдельные файлы по каждой команде с иерархией директорий, соответствующей подкомандам
- Доступ к документации из cli
  - dapp help build
  - dapp help stages cleanup local
  - dapp help <полное название команды с подкомандами>
- Если текста влезает в терминал — выводить просто текст
- Если текст не влезает в терминал — выводить в PAGER
  - Как в git
- Выключать цвета, если терминал не интерактивный

Оригинальный issue-запрос: https://github.com/flant/dapp/issues/9.

**Comment by diafour** [comment]
just fyi
- Если текст не влезает в терминал — выводить в PAGER
  - Как в git

git запускает man, который запускает $MANPAGER и потом $PAGER

А на винде git help branch, набранный из консоли запускает браузер со страницей типа https://git-scm.com/docs/git-branch - тот же man, только в вебе.

**Comment by distorhead** [comment]
Пока отказываемся.
