### ISSUE TITLE
Директивы семейства depends_on должны использовать файлы из git

### ISSUE THREAD

**Issue by alexey-igrychev** [flant/dapp#55]
Как релиз-инженер приложения, я хочу настраивать файлы зависимости для пересборки образа с определенной стадии при описании git-артефактов, в которых содержатся эти файлы, чтобы:

- Повысить степень модульности при описании git-артефакта
  - После удаления блока описания git-артефакта Dappfile останется корректным (не будет depends_on привязанных к файлам, которых уже нет)
- Повысить понятность описания конфигурации
  - Сразу понятно из какого git артефакта берется файл, указанный в depends_on
    - Не нужно заглядывать в файловую структуру, чтобы узнать из какого артефакта этот файл
- Ограничить выбор файлов-зависимостей только теми файлами, которые добавляются через git-артефакты (еще файлы могут быть добавлены, например, рецептами)
  - Убавятся возможности для создания некорректных конфигураций случайным образом (когда для depends-on используются файлы не из git-артефактов)
- Чтобы можно было пересобирать образы при изменениях в external git artifact’ах.

_Детали реализации_
- Переехать в dsl в группу git
- => Триггер сборки по external-git
- Пример:
```
dimg 'front-backend-aggregation' do
  docker.from 'docker-registry.local/mosru-centos7:7'

  artifact do
    chef.dimod 'mdapp-front'

    git do
      add '/' do
        owner 'root'
        group 'root'
        to '/app/'

        stage_dependencies do 
          install 'bower.json', 'package.json'
          artifact_build '.yo-rc.json', 'Gruntfile.js', 'gulpfile.js', 'src', 'version.txt'
        end
      end
    end

    export '/app/' do
      after 'setup'
      owner 'root'
      group 'root'
      to '/app/'
    end
  end

  chef.dimod 'mdapp-mail', 'mdapp-nginx'
  chef.recipe 'main'
end
```

**Comment by distorhead** [comment]
Решили в рамках этого же issue добавить поддержку стадии before_setup с milestone 0.10.
