### ISSUE TITLE
Указание mount, depends_on не только в Dappfile, но и прямо в chef-рецептах

### ISSUE THREAD

**Issue by alexey-igrychev** [flant/dapp#57]
Как релиз-инженер (chef-приложения) я хочу, когда пишу в рецепте код, результат выполнения которого зависит от внешнего контекста (файлов добавляемых через git artifact), иметь возможность сразу указать эту зависимость, а не указывать ее отдельно в Dappfile.

Как релиз-инженер (chef-приложения) я хочу, когда пишу в рецепте код, результат выполнения которого зависит от наличия определенных mount'ов, иметь возможность сразу указать эти mount'ы, а не указывать их отдельно в Dappfile.

_Детали реализации_
Предусмотреть какой-то специальный синтаксис в комментариях, например “#STAGE_DEPENDENCIES: /app/compose.json”, который автоматически парсить и учитывать. В контексте того, что мы хотим перенести depends_on в git, тут пути можно указывать “внутри образа” и предусмотреть механизм обратного разрешения (из пути-в-образе в git artifact и путь в нем).

Однако, есть ощущение что комментарии в чистом виде не подойдут, так-как со захочется разрабатывать универсальные mdapp’ы, пути в которых зависят от атрибутов.

**Comment by diafour** [comment]
chef builder is deprecated
