### ISSUE TITLE
Не читаются файлы из .dappfiles

### ISSUE THREAD

**Issue by rjeka** [flant/dapp#620]
Здравствуйте !
Согласно [документации к версии dapp 0.27.0](https://github.com/flant/dapp/blob/master/docs/rfc/yaml_with_ansible.md) dapp должен читать yaml файлы из .dapfiles. Но либо я что то не так делаю, либо файлы не читаются 

`dapp --version`
`dapp: 0.27.0`

`ls -a`
`.  ..  .dappfile.render.yaml  .dappfiles  dappfile.yaml`

`ls -a .dappfiles/`
`.  ..  app.yaml`

`cat dappfile.yaml`
`dimg: hello`
`from: ubuntu:16.04`
`ansible:`
`  beforeInstall:`
`    - debug: msg='Before install'`
`  install:`
`    - debug: msg='Install'`

` cat .dappfiles/app.yaml ` 
` dimg: app` 
` from: centos:7` 
` ansible:` 
 `  install:` 
`   - debug: msg='Install'` 
`   - yum:` 
`       name: mc` 
`       state: latest` 

Запускаю build 

`/test$ dapp dimg build`
`hello`
`  hello: calculating stages signatures`                                                                                                                                                    `[RUNNING]`
 ` hello: calculating stages signatures`                                                                                                                                                         `[OK] 0.0 sec`
 ` From ...  `                                                                                                                                                                                   `[OK] 1.84 sec`
`    signature: dimgstage-`
`test:b3fba727e2fd0bafe9368bc46768aa625ebd6f534e9ba4e5b7058d1dae278dba`
`  Before install`                                                                                                                                                                         `[BUILDING]`
`debug msg`
`Before install`
 ` Before install    `                                                                                                                                                                           `[OK] 2.66 sec`
   ` signature: dimgstage-test:ee9a17f6adbb04d2dd6753fd3031e2d723ad8adc8a75e8c3b3362495a033fec8
    commands:
      /.dapp/deps/ansible/2.4.4.0-10/embedded/bin/ansible-playbook /.dapp/ansible-workdir/playbook.yml 
  Install group
    Install                                                                                                                                                                              [BUILDING]
debug msg
Install
    Install                                                                                                                                                                                    [OK] 2.7 sec
      signature: dimgstage-test:77c62b717f0168113b384ea488cfedbf18c2c220c9242ea45020a5ad4fe7a9ec`
`      commands:`
`        /.dapp/deps/ansible/2.4.4.0-10/embedded/bin/ansible-playbook /.dapp/ansible-workdir/playbook.yml `

Собрался только hello образ

 `$ dapp dimg list `
 `hello `
 `Running time 0.02 seconds `

**Comment by distorhead** [comment]
Приветствуем!

Косяк в том, что в анонсе в telegram-канале была предоставлена ссылка на proposal, а не на документацию. В proposal описано несколько больше, чем реализовано. Так вот `.dappfiles` не реализовано, это было добавлено в proposal как идея для обсуждения. Реализовано лишь описание либо в `dappfile.yml`, либо в `dappfile.yaml`.

Вот ссылка на краткую актуальную документацию по yaml: https://github.com/flant/dapp/blob/master/docs/yaml.md.

Тем не менее в proposal описаны "почему" некоторые моменты сделаны так как сделаны, поэтому с ним тоже полезно ознакомиться.

Извинения за то что сбили с толку.

**Comment by distorhead** [comment]
Если наберется достаточно много "голосов" за идею с `.dappfiles`, то реализуем в будущих релизах, как-то так.

**Comment by rjeka** [comment]
Спасибо за оперативный ответ. Я чего то сам не заметил что это предложения )))
А нет ли идеи реализации подтягивания плейбуков из отдельных yaml файлов, по аналогии с chef  ??? 
Я так понимаю, что на данном этапе использование в dappfile.yaml что shell, что ansible практически одинаково ????

**Comment by distorhead** [comment]
Ansible сборщик может быть удобен для:

* Описания инструкций сборки чисто по документации ansible, без ручного залезания в образ для проверки. Когда используешь некий модуль ansible по документации есть некая гарантия, что task выполнит то что описано, некая декларативность. Если используешь shell, то пока не проверишь руками что там получилось, нет уверенности.
* Переноса уже существующих task'ов из playbook, который раньше настраивал виртуалку, для настройки образа.

Сейчас с ansible есть такой момент, что не всё множество модулей проверено и допущено к использованию в dappfile. Но этот список допущенных мы дополним со временем.

В остальном да, все можно делать и через shell.

**Comment by diafour** [comment]
При использовании shell для некоторых вещей приходится ставить дополнительные пакеты.

- в dapp есть поддержка `become_user`, т.к. для ansible собран свой sudo в dappdeps. В shell сборщике этого нет: если в образе нет sudo, то и запустить команды от пользователя не получится. В ubuntu есть sudo, в alpine, centos нет, но через ansible смена юзера работает независимо от `docker.from`.
- в ansible есть модуль `get_url` и он работает без дополнительных пакетов в образе. Используя shell-сборщик, приходится ставить curl или wget где-нибудь в before_install, чтобы скачать файл или архив.  В alpine есть wget,в centos — curl , а в ubuntu надо что-то установить. Через ansible можно скачивать везде одинаково.

**Comment by rjeka** [comment]
Дмитрий Столяров, в своем выступлении на rootconf, которое выложено на [youtube](https://www.youtube.com/watch?v=8R5UDg29Vic&t=1744s), говорил, что Вы добавили реализацию подключения chef cookbook для того что бы уйти от постоянного копипаста, как в случае с shell.
Возможно ли такое с ansible ??? Например у ansible есть инструменты include_tasks, import_playbook, import_tasks. Было бы удобно описывать плейбуки, таски или роли в отдельном yaml. Хранить их в  например в каталоге  REPO_ROOT/.dappfiles/., а подключать как в ansible c помощью [include](http://docs.ansible.com/ansible/latest/include_module.html)  А в идеале бы вообще из gitlab по аналогии с реализованной сейчас директивой git.

**Comment by alexey-igrychev** [comment]
@rjeka, https://flant.github.io/dapp/reference/build/dappfile.html#organizing-dappfile-configuration
Available since [0.36.3](https://github.com/flant/dapp/pull/1089)
