### ISSUE TITLE
Documentation ! only Russian

### ISSUE THREAD

**Issue by wizard580** [flant/dapp#643]
Приветствую.
Проект интересный, пробуем внедрять. Спасибо.

Но, документация на русском - это как-бы не фонтан. AFAIK английский - устоявшийся стандарт, разве нет?
Пример: в нашей компании русскоязычного населения менее 30%, а распространять придется среди всех. 

Можно ли рассчитывать на исправление этого досадного недоразумения?

Спасибо.

**Comment by distorhead** [comment]
Знаем, для новых кусков уже пишем на англ., вот например для yaml+ansible: https://github.com/flant/dapp/blob/master/docs/yaml.md.

Вопрос уже много раз у нас поднимался, задача по переводу есть. Понемногу будем переводить + саму доку надо перерабатывать в лучшую сторону.

**Comment by may-cat** [comment]
Занимаюсь вопросом, в течение августа надеемся перевести все статьи.
