### ISSUE TITLE
Global ansible variables support

### ISSUE THREAD

**Issue by distorhead** [flant/dapp#649]
For now only tasks section from playbook is accepted as ansible config. There may be need to define global `vars` section. Workaround for now is module `set_fact`.

**Comment by diafour** [comment]
Use case described in #188

**Comment by diafour** [comment]
Workaround from @dapp_ru:

ANSIBLE_ARGS="-e extra_vars" dapp dimg build

extra_vars then can be used in jinja templates

**Comment by distorhead** [comment]
Close in favor of https://github.com/flant/dapp/issues/188
