### ISSUE TITLE
не корректно работает git add при работе с субмодулями

### ISSUE THREAD

**Issue by kobel169** [flant/dapp#684]
При использовании конструкции 
```
      add '/src/data' do
        to '/new/path'
      end
```

При условии что /src это субмодуль, то в конечном образе по пути /new/path мы видим дерево каталогов /new/path/src/data, когда без субмодулей мы видим ожидаемое дерево /new/path/data

**Comment by alexey-igrychev** [comment]
в версиях 0.27.17 и 0.28.3 фикс https://github.com/flant/dapp/pull/677.

**Comment by kobel169** [comment]
Воспроизвёл неожиданное поведение в https://github.com/kobel169/dapp-submodule-spec-project-branches/blob/master/Dappfile 
```
root@1c069a4e0fc8:/# ls root/
dapp-submodule-spec-project-test  sup
```

```
$ dapp --version
dapp: 0.28.3
```
