### ISSUE TITLE
`dapp create APP` command: generate typical dapp files by APP name

### ISSUE THREAD

**Issue by distorhead** [flant/dapp#708]
* Create samples directory in the root of github.com/flant/dapp `master`: `/samples`.
* Use case scenario:
    * User want to do kubernetisation of some app.
    * User runs `dapp create typical-js-app` in some js application git directory.
    * Dapp downloads files from `master:/samples/typical-js-app` and places them in the current directory.

**Comment by diafour** [comment]
Application templates stores in /samples in the individual directories. Each directory name is an application template name. 

`dapp create --list` — list available application templates
`dapp create app-tmpl-name` — copy files from

**Comment by distorhead** [comment]
#747
