### ISSUE TITLE
_minikube_wait_till_ready stucks

### ISSUE THREAD

**Issue by kobel169** [flant/dapp#724]
Попытка minikube setup не проходит успешно т.к. на этапе https://github.com/flant/dapp/blob/master/lib/dapp/kube/dapp/command/minikube_setup.rb#L118 
Получается эксцепшн conn refused, хотя по факту Excon вот тут https://github.com/flant/dapp/blob/master/lib/dapp/kube/kubernetes/client.rb#L204 ругается на невалидный сертификат.  что приводит к неработоспособности dapp kube minikube setup

**Comment by distorhead** [comment]
Вроде на данный момент все ok. Раньше могли использоваться неправильные настройки. Пока снимаю с milestone.
