### ISSUE TITLE
dapp minikube deploy fails

### ISSUE THREAD

**Issue by kobel169** [flant/dapp#726]
Деплой после dapp minikube setup падает по причине отсутствия в кластере minikube установленного helm

**Comment by distorhead** [comment]
Helm должен быть установлен туда же, где стоит dapp, на хост-машину. Как kubectl с хост машины работает, также должен работать и helm.

**Comment by kobel169** [comment]
@distorhead Я говорю о отсуствии в кластере поднимаемом миникубом пода тиллера
