### ISSUE TITLE
Иллюстрация процесса установки cookbook'а в стадию для сборочного контейнера

### ISSUE THREAD

**Issue by distorhead** [flant/dapp#86]
Релиз-инженеру приложения нужна иллюстрация процесса установки файлов сборочного cookbook'а и dimod'ов в стадию для сборочного контейнера, чтобы иметь под рукой быструю, понятную и самодостаточную справку по правилам именования файлов cookbook'а и dimod'а во время описания правил сборки приложения.

**Comment by diafour** [comment]
chef builder is deprecated
