### ISSUE TITLE
Префикс 'docker.io/' в имени репозитория образа

### ISSUE THREAD

**Issue by kobel169** [flant/dapp#93]
When i using dapp on CentOS 7 with docker 1.10.3 i got next error 
```
$ dapp build --verbose
pulling image `ruby:2.3-alpine`                            [RUNNING]
Trying to pull repository docker.io/library/ruby ... 2.3-alpine: 
Pulling from docker.io/library/ruby
Digest: sha256:a0edc9fa6ce63e1a33475cb8a1097ec961d45597f2972242ef2d5187ba7bedf6
Status: Image is up to date for docker.io/ruby:2.3-alpine
pulling image `ruby:2.3-alpine`                             [OK] 1.9 sec
Stacktrace dumped to /tmp/dapp-stacktrace-7e12a2f5-89ea-4e1e-bfb5-0b21bcd6553e.out
Image `ruby:2.3-alpine` not found!
```

Used next Dappfile
```
dimg do
  docker.from 'ruby:2.3-alpine'
  shell do
    before_install do
      run '/bin/sh -c ls'
    end
  end

  git do
    add '/' do
      to '/app'
    end
  end
end
```

When i change docker.from to `docker.io/ruby:2.3-alpine` build sucessfuly starts 

But on ubuntu 14.04/16.04 works both records.

**Comment by distol** [comment]
Закрываю в пользу #45 .

**Comment by distol** [comment]
Ошибочно закрыли, никак не связано с #45.

**Comment by distorhead** [comment]
Связан с #94.

**Comment by kobel169** [comment]
@alexey-igrychev  Касательно https://github.com/alexey-igrychev/dapp/commit/3ded217a971159c8459ad0b4661d7bf8e6308e7a Это решит только часть проблемы, т.к. аналогичное поведение с частными registry. Напр.: 192.168.0.15:5000/image:tag

**Comment by alexey-igrychev** [comment]
@kobel169
различное поведение докера при скачивании из публичного хаба сейчас решается удалением префикса, а в последствии переход на использование Docker Api, где это унифицировано, решит вопрос и с частными registry.

**Comment by distorhead** [comment]
@kobel169 А какое поведение ожидается если используется частный registry `192.168.0.15:5000`? В docker.from надо явно указывать `192.168.0.15:5000/image:tag` или `docker-registry/<image>:<tag>`, а docker-registry определять в /etc/hosts.

Проблема, которая тут возникла связана с тем, что docker автоматом подставляет docker.io. А поведение утилиты docker для образов из docker.io отличается на ubuntu и centos. В частности, сейчас dapp делает листинг существующих образов через вызов `docker images`, а не через API, и получает разный результат на centos:7 и ubuntu. Если использовать API — список будет на обеих системах одинаков. Поэтому решения 2:
* Переводить на API
* Отрезать docker.io в коде получения этого списка образов.

Переводить на API надо в любом случае, но решили, что позже. Поэтому пока отрезаем префикс docker.io.

**Comment by kobel169** [comment]
На мой взгляд самой простой затычкой которая решит всё, будет отрезание, но умное. 

Типа такого 

```
require 'resolv'
unless Resolv.getaddresses(name.split("/")[0].split(":")[0]).empty?
  name = name.split("/")[1..-1].join("/")
end
```

Если это ip или домен который резолвится то мы это убиваем, аналогично проверяем ip:port без порта.
