### ISSUE TITLE
"no such file or directory" when using alpine image

### ISSUE THREAD

**Issue by kobel169** [flant/dapp#94]
Hi, i use dapp 0.8 and have the following error when use alpine image:
```
$ dapp build --verbose
From ... Launched command: `/.dapp/deps/base/0.1.14/bin/true`     [FAILED] 0.35 sec
  signature: dimgstage-app:bcfd3aaae097f5c2d2719ed759fc0f1dedc694eba6f18e68a7dc21a27c9011b2
Stacktrace dumped to /tmp/dapp-stacktrace-1074b848-d03d-438e-838c-04a9ef80e32c.out
>>> START STREAM
no such file or directory
docker: Error response from daemon: Cannot start container 731a8f66cf0220267802d09f90082d0ec9160df49d689a2142befc0ff46ba359: [9] System error: invalid character 'r' looking for beginning of value.
>>> END STREAM
```

I use the following Dappfile:
```
dimg do
  docker.from 'docker.io/ruby:2.3-alpine'
  git do
    add '/' do
      to '/app'
    end
  end
end
```

**Comment by distol** [comment]
Выглядит так, как буд-то проблема с glibc очень просто разрешима. Нужно просто пересобрать наши dappdeps с максимально древним glibc и все заработает. Несколько ссылок:
1. https://github.com/phusion/traveling-ruby#why-not-just-statically-link-the-ruby-binary
2. https://sourceware.org/glibc/wiki/Glibc%20Timeline
3. https://tickets.opscode.com/browse/CHEF-5020

**Comment by distol** [comment]
Так, тут дело вообще не в libc, а в неправильно работающем docker.from у нас. Свяазно с #93.

**Comment by alexey-igrychev** [comment]
проблема связана с конфликтом между системными и alpine-овскими docker-инструкциями.

**Comment by distorhead** [comment]
Анализ проблемы выявил вероятную связь проблемы с отсутствием стандартного libc в alpine. Проблема связана с #45. Если не решиться после #45, будем думать.

**Comment by distorhead** [comment]
Продолжаем в 0.13 в этом issue #164
